<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<InvariantGlobalization>true</InvariantGlobalization>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<PublishAot>true</PublishAot>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\JobsDbLibrary\JobsDbLibrary.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="../stylecop.json" />
	</ItemGroup>

</Project>
